ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "token" TEXT;
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "internalId" TEXT;
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "failedReason" TEXT;
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "operator" TEXT;